### ISSUE TITLE
Referenced gitlab raw/master/data/data.min.json no longer exists

### ISSUE THREAD

**Issue by oconnedk** [ClearURLs/Addon#103]
Top of [README.md](https://github.com/ClearURLs/Addon/blob/master/README.md) has this:

> This extension will automatically remove tracking elements from URLs to help protect your privacy when browse through the Internet, which is regularly updated by us and can be found [here](https://gitlab.com/KevinRoebert/ClearUrls/raw/master/data/data.min.json).

The **here** link (https://gitlab.com/KevinRoebert/ClearUrls/raw/master/data/data.min.json) is no longer valid. Looks like it was deleted from the GitLab project a while back

**Comment by KevinRoebert** [comment]
I've fixed this. It was pointing to the old location.
