### ISSUE TITLE
Why does the extension need the download permission ?

### ISSUE THREAD

**Issue by alvinometric** [ClearURLs/Addon#107]
Hello,

Thank you so much for creating this! I was really close to coding something similar recently after copying a link with way, way too many `UTM`s.

There's one thing that really puts me off in the extension though.

On Firefox, it says that it requires the permission to: 

"Download files and read and modify the browser’s download history"

Why is this needed? Most of my extensions only use "Access your data for all websites"

The helper page with all the Firefox permissions [seems to indicate](https://support.mozilla.org/en-US/kb/permission-request-messages-firefox-extensions) that this permission is about downloads.

(Incidentally, the Mozilla support sites uses `utm` links 😅 🦊 )

Thanks,
Alvin

**Comment by KevinRoebert** [comment]
See: https://github.com/ClearURLs/Addon#permissons or https://gitlab.com/KevinRoebert/ClearUrls/-/issues/159
