### ISSUE TITLE
Unable to install - addon corrupted error

### ISSUE THREAD

**Issue by mdziczkowski** [ClearURLs/Addon#118]
I can't install and getting the "Installation aborted because the add-on appears to be corrupt." error

**Comment by netalvesj** [comment]
Same here...

**Comment by user0022** [comment]
Hello!
I had also this issue, usual clicking in Firefox addon page said:
"The add-on downloaded from this site could not be installed because it appears to be corrupt"

This yesterday, and today when trying again, in IceCat (Firefox fork) which I just installed yesterday. Under Lubuntu 18.04 32 bits.
IceCat seems on the brink of updating from 60.7.0 to 78.xx.0, and if the problem comes from the browser (perhaps, I think), this update might fix it? I will tell if I see.

I installed this addon months ago in Firefox and it's been OK. I didn't test remove and reinstall, for fear to get the same refusal.

**Comment by 3nprob** [comment]
In Firefox 96 (compiled to allow unsigned add-ons), I get the same result by attempting to install `ClearURLs.zip`, either downloaded from CI or self-packaged. Installing from Mozilla store works.

**Comment by 3nprob** [comment]
I have confirmed this is not due to signing - `xpinstall.signatures.required` is set to `false` and I can successfully install other unsigned self-packaged add-ons.

**Comment by 3nprob** [comment]
Adding and `applications` field to `manifest.json` and using `7z` instead of `zip` to package (internal ordering of files is different) and it will now add properly

**Comment by mdziczkowski** [comment]
> Adding and `applications` field to `manifest.json` and using `7z` instead of `zip` to package (internal ordering of files is different) and it will now add properly

we will see. There could be also another, hidden reason of the error and it need to be checked frequently if it works as it should

**Comment by 3nprob** [comment]
@mdziczkowski Does it resolve it for you as well?

**Comment by mdziczkowski** [comment]
@3nprob Need to test it to tell

**Comment by KevinRoebert** [comment]
> Adding and applications field to manifest.json and using 7z instead of zip to package (internal ordering of files is different) and it will now add properly

Sounds weird. I'll take a closer look at this. When developing or debugging the addon, I always import from the ZIP and so far I have never encountered any errors.

Does the error also occur when you use the automatically packed version from the GitHub release? https://github.com/ClearURLs/Addon/releases/download/1.22.0/ClearURLs-v1.22.0.zip

Or the signed version xpi version? https://github.com/ClearURLs/Addon/releases/download/1.22.0/clearurls-1.22.0-firefox.xpi

**Comment by mdziczkowski** [comment]
@3prob ok, it got installed and it seem to kinda work, but "cleaning up" of the put input  URL's return exactly the same address

**Comment by KevinRoebert** [comment]
@3nprob Could you please share your manifest.json? Unfortunately, I can't find any official support for the `applications` field.

**Comment by 3nprob** [comment]
@KevinRoebert I haven't isolated the minimum-viable change to make the zip go from "corrupt" to "installing" but I replaced `manifest.json` with that from the xpi in Firefox store (only notable change is escaping of your name) and added:

```
  "applications": {
    "gecko": {
      "strict_min_version": "54.0a1",
      "id": "1af473f86ca35bf1fb8e795b1217834bf97dffd9@clearurls"
     }
  }
```

(id generated through installing as temporary as above; not sure if you can just put an arbitrary string there or not)

**Comment by 3nprob** [comment]
the command I used: `7z a ./ClearURLs.xpi -r  clearurls.js browser-polyfill.js manifest.json img/* external_js/* html/* core_js/* css/* fonts/* _locales/*`

**Comment by KevinRoebert** [comment]
@3nprob @mdziczkowski I've uploaded an updated version of the `manifest.json` could you check if this does resolve the bug?

**Comment by mdziczkowski** [comment]
@3nprob The installation got correctly and I'm testing it.

The problem I had found (as already described) that when using the "clear url" tool of the plugin, the input and generated output are the same

**Comment by 3nprob** [comment]
@KevinRoebert No dice. Adding the `applications` field makes it work, though. Switching to `7z` does not seem necessary.

**Comment by 3nprob** [comment]
I guess the one thing to determine is a reasonable min_version. How about ESR (78.0, June 2020)?

**Comment by KevinRoebert** [comment]
Could you try the following:

```json
"applications": {
        "gecko": {
            "id": "{74145f27-f039-47ce-a470-a662b129930a}"
        }
    }
```

**Comment by 3nprob** [comment]
Yup, works fine :+1:

**Comment by 3nprob** [comment]
> The problem I had found (as already described) is that when using the "clear url" tool of the plugin, the input and generated output are the same

@mdziczkowski That sounds like a separate issue

**Comment by KevinRoebert** [comment]
Could you please try this version? https://gitlab.com/KevinRoebert/ClearUrls/-/jobs/artifacts/master/raw/ClearURLs-firefox.zip?job=bundle%20addon%20firefox

**Comment by 3nprob** [comment]
@KevinRoebert Huge success!

**Comment by KevinRoebert** [comment]
@mdziczkowski Could you confirm this?
