### ISSUE TITLE
Bug: Google Drive Videos

### ISSUE THREAD

**Issue by 8227846265** [ClearURLs/Addon#120]
Hi, I just would like to report a bug as this has been occurring for the past several months and was reported via GitLab before, but it seems it's not yet available on GitHub.

**The Issue:**

- If you have ClearURLs enabled, and you play a video on Google Drive. It won't play
- Disabling ClearURLs and the video will then play.

**Comment by matejdro** [comment]
Possibly Related: Extension is also causing Google Sheets to not load fully (at least Macros, Script Editor and "More date and time formats" are not working, but possibly more).
