### ISSUE TITLE
Question about connection.

### ISSUE THREAD

**Issue by kajlando** [ClearURLs/Addon#130]
Why ClearURLs connects to "rules2.clearurls.xyz" on start?

**Comment by KevinRoebert** [comment]
ClearURLs downloads the current rules file at startup. There are several sources for this. We host the rules once at GitHub-Pages and once at GitLab-Pages. See also the article in the documentation.

However, the rules can also be hosted on a local server. The URL can be changed to another server in the settings at any time.

In the ClearURLs version v.2 the possibility should be added that you can switch off the download of the most current rules completely and always update the rules manually.
