### ISSUE TITLE
ClearURLs Addon Error? ETag Tracking

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [ClearURLs/Addon#138]
1.
ClearURLs Addon Error?
ETag Tracking not stopped on:

Cookieless cookies
https://lucb1e.com/randomprojects/cookielesscookies/
--------
2.
Are these sources OK?

data.json
https://rules2.clearurls.xyz/data.minify.json

Request types
main_frame,sub_frame,xmlhttprequest
-----
thx :)

**Comment by KevinRoebert** [comment]
Should be fixed
