### ISSUE TITLE
find definition/reference feature on github.com is blocked

### ISSUE THREAD

**Issue by drahnieR** [ClearURLs/Addon#155]
Hi, it seems that `([\/\?#]|(&|&))+((?:%3F)?ref_?=[^&]*)` is blocking github's find definition/reference feature

Before processing
`https://github.com/lodash/lodash/find-definition?q=Array&blob_path=flattenDepth.js&ref=master&language=JavaScript&row=9&col=13`
After processing
`https://github.com/lodash/lodash/find-definition?q=Array&blob_path=flattenDepth.js&language=JavaScript&row=9&col=13`

click baseFlatten here and you should be able to see this feature in action
https://github.com/lodash/lodash/blob/master/flattenDepth.js#L28

**Comment by dufferzafar** [comment]
@drahnieR Did you figure out a workaround for this?

**Comment by drahnieR** [comment]
> @drahnieR Did you figure out a workaround for this?

Not sure about earlier versions, but this seems to be fixed now
