### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by atomGit** [ClearURLs/Addon#165]
i think developers are under-appreciated much of the time, so i just dropped by to say thanks for your work ... i appreciate it

**Comment by KevinRoebert** [comment]
Thank you for your kind words.

Merry Christmas and a happy new year.

**Comment by wiredsource** [comment]
Nice work! Thank you. 
I was considering coding something similar until I just spotted your extension here. My use case was more that I was annoyed by the bloated urls while sharing. I did do the clean manual every time I would share anything. 

anyways great job!

**Comment by atomGit** [comment]
what's sad is that an extension like this is even necessary - the www has devolved into a cluster-f'k run by idiots paying off their college debts

a good read...

[So-called modern web developers are the culprits](https://unixsheikh.com/articles/so-called-modern-web-developers-are-the-culprits.html)
