### ISSUE TITLE
Recursive or Deep Cleaning

### ISSUE THREAD

**Issue by ralphocdol** [ClearURLs/Addon#172]
When I try to use Copy Clean Link Location or even clean the URL within the extension from let say facebook, it will only clean once but the output still has a dirty URLs attached to it like this one: 
![CleanURLs cleaning tool 1](https://user-images.githubusercontent.com/31056871/153643846-612c8b6a-031d-4170-9ba4-a2648263c117.png)

The generated link still has a dirty **?fbclid** attached to it which can be clean by pasting it again, but it's not how it is in context menu 
![Copy Clean Link Location](https://user-images.githubusercontent.com/31056871/153644576-84339778-f8b3-46fc-9d96-a1c0d7c25627.png).

A deep cleaner with number of steps/recursion would be a good choice for this

**Comment by KevinRoebert** [comment]
Resolved/Added by https://github.com/ClearURLs/Addon/commit/b2a9333611897ae11a17401e2e6d0ac7cde8adb5
