### ISSUE TITLE
Twitter URL's not being cleared

### ISSUE THREAD

**Issue by amalic** [ClearURLs/Addon#181]
Twitter has recently added a tracking id to it's URL's when selecting the Copy Link option after pressing the Share button on tweets.

It looks like this
`https://twitter.com/<user_of_tweet_to_be_shared>/status/<tweet?id>?s=<DEVICE_IDENTIFIER>&t=<TRACKING_ID>`

The URL can be sanitized by removing everything after the question mark. Please add this to your config file.

**Comment by amalic** [comment]
Didn't read the README file first :)

**Comment by CharlesChiuGit** [comment]
Hi, @amalic May I ask what did you find in the readme about the twitter url not being shorten?

**Comment by amalic** [comment]
Not sure any more tbh
