### ISSUE TITLE
Unrecognized manifest key 'applications' when installing unpacked 1.23.1

### ISSUE THREAD

**Issue by gjf** [ClearURLs/Addon#184]
Unrecognized manifest key 'applications'.
  _"applications": {
    "gecko": {
      "id": "{74145f27-f039-47ce-a470-a662b129930a}"
    }
  },_

The issue is observed when installinh unpacked 1.23.1 (because ncrx file was not released yet).
However addon seems working.

**Comment by KevinRoebert** [comment]
thanks for the hint. Forgot to include jq into the CI, therefore this was not removed from the ZIP for Chrome. I'll upload a new version quickly.

**Comment by KevinRoebert** [comment]
Does the new uploaded version work? https://github.com/ClearURLs/Addon/releases/download/1.23.1/ClearURLs-1.23.1-chrome.zip

**Comment by gjf** [comment]
Yup this one is good.
Thank you!
