### ISSUE TITLE
Gmail browsing broken with ClearURLs 1.24.1

### ISSUE THREAD

**Issue by maxxyme** [ClearURLs/Addon#193]
Let's say I'm on my first Google account's Gmail inbox: https://mail.google.com/mail/u/0/#inbox

Typing "searchterm" in the search field + Enter redirects to this URL:
https://mail.google.com/mail/u/0/#search/searchterm
When browsing back (backward history button), goes back to:
https://mail.google.com/mail/u/0/#inbox
and displays again my Inbox.

With ClearURLs 1.24.1 activated, doing the same displays the search results, but ends up at this URL: https://mail.google.com/mail/u/0/#search%2Fsearchterm=
And unfortunately, when browsing back it goes indeed to this URL:
https://mail.google.com/mail/u/0/#inbox=
but the Gmail UI isn't refreshed/updated, and stays on the search results.

**Comment by maxxyme** [comment]
> Duplicate of #191?

Might be the same issue though...

**Comment by archetyped** [comment]
Looks like disabling the "Prevent tracking injection over history API" option in ClearURLs preferences allows Gmail to function properly again.

Hopefully this is fixed fully though without needing to disable this option globally.

A whitelist or per-domain settings would be great for ClearURLs.

**Comment by maxxyme** [comment]
Seems to fix. Thanks for pointing this setting!

**Comment by Schweinepriester** [comment]
Probably fixed with 1.25.0 now?

**Comment by KevinRoebert** [comment]
I hope so. Can you verify that?

**Comment by maxxyme** [comment]
Seems OK to me, I have 1.25.0 and can navigate in Gmail as before, even with the option "Prevent tracking injection over history API" checked.
