### ISSUE TITLE
[Bug] Dark mode font in the log is messed up

### ISSUE THREAD

**Issue by NoMeansNowastaken** [ClearURLs/Addon#207]
I am on Firefox 100 with clearurls 1.24.1

![image](https://user-images.githubusercontent.com/77455871/168202971-12ca5cbe-17ab-4ca0-9d73-2723ff10abd4.png)

**Comment by KevinRoebert** [comment]
Fixed in https://github.com/ClearURLs/Addon/commit/a930a94224e35d2cc8146d34d61f34a9a0581033
