### ISSUE TITLE
It broken all docsify's website

### ISSUE THREAD

**Issue by HaveF** [ClearURLs/Addon#216]
I find ClearURLs 1.24.1(don't know about other version) break the docsify's page. When I open url https://selfrefactor.github.io/rambda/, it will change the url to https://selfrefactor.github.io/rambda/#%2F=, after that, all link in the page broken...

Of course, the extension broken https://docsify.js.org/ page too = =;

When I open `https://docsify.js.org/#/`, the extension will change the url to `https://docsify.js.org/#%2F=`, after that, all links broken

**Comment by maxxyme** [comment]
Please try this: https://github.com/ClearURLs/Addon/issues/193#issuecomment-1097167330

**Comment by HaveF** [comment]
Oh, it works after restart extension, I thought the option will works while I was click. Thanks!
