### ISSUE TITLE
ClearURLs breaks functionality of YouTrack

### ISSUE THREAD

**Issue by TobiasKnauss** [ClearURLs/Addon#233]
See my bug report in YouTrack. It turned out that it was not their system, but this addon.
https://youtrack.jetbrains.com/issue/JT-70014

**Comment by maxxyme** [comment]
Maybe check solution provided here... https://github.com/ClearURLs/Addon/issues/193

**Comment by TobiasKnauss** [comment]
No, this does not help. You can test yourself easily, you don't need an account there.

**Comment by TobiasKnauss** [comment]
I have to correct myself: It does help.

I had trouble hitting the save button because of some line-break / scrollbar issue in the settings of the addon: The view flickers with about 5 per second between
![grafik](https://user-images.githubusercontent.com/18487427/181708820-d3ff7bfc-e5a0-43a0-a3f4-7b3383ae663b.png)
and
![grafik](https://user-images.githubusercontent.com/18487427/181708944-0b67f2db-6d5d-44a1-9cc0-e131c6f56710.png)
which makes it hard to change any setting because the position of the elements changes with the same frequency.
Maybe an issue of your addon, maybe an issue of firefox, don't know. However, it's another issue.

**Comment by zotabee** [comment]
> I have to correct myself: It does help.
> 
> I had trouble hitting the save button because of some line-break / scrollbar issue in the settings of the addon: The view flickers with about 5 per second between ![grafik](https://user-images.githubusercontent.com/18487427/181708820-d3ff7bfc-e5a0-43a0-a3f4-7b3383ae663b.png) and ![grafik](https://user-images.githubusercontent.com/18487427/181708944-0b67f2db-6d5d-44a1-9cc0-e131c6f56710.png) which makes it hard to change any setting because the position of the elements changes with the same frequency. Maybe an issue of your addon, maybe an issue of firefox, don't know. However, it's another issue.

Thanks for the information.
