### ISSUE TITLE
Endless redirects in application

### ISSUE THREAD

**Issue by xf-** [ClearURLs/Addon#243]
**Description**
YouTrack allows filtering and adds the query into URL and clear URLs breaks it (at least deactivating fixes it).

**Problem**
This results in a fight between the application and add-on resulting in endless History entries/redirects and unusable application (clicked links won't respond)

It replaces the space with + and reverts, same goes for other characters.

**Example**
(Public instance)
Searching for redirect issue on JetBrains YouTrack (same issue on self-hosted instance)
https://youtrack.jetbrains.com/issues/YTM?q=redirect%20issue

This could be a problem in more JS framework applications which monitor the URL and won't do a full reload.

**Comment by Baryczka** [comment]
Try to disable `Allow domain blocking (Can lead to problems on pages that do not allow AdBlockers)`
It helped me. Check also: #233

**Comment by xf-** [comment]
> Try to disable `Allow domain blocking (Can lead to problems on pages that do not allow AdBlockers)` It helped me. Check also: #233

THX - close it for now, but seems still wrong

**Comment by Baryczka** [comment]
Hm in fact I was wrong, what helped me was: `Prevent tracking injection over history API (See also: [The replaceState() method]`. Remeber to save&reload addon and page after change
And I agree, whitelist for some domains would help.
