### ISSUE TITLE
Please make the extension available on Firefox Android

### ISSUE THREAD

**Issue by balazsgerlei** [ClearURLs/Addon#247]
I'm not sure what is needed for an extension to appear in the Android version of Firefox, but I see that it is (currently) a very limited list. This extension is very useful and would be maybe even more useful on mobile where a lot of my contacts regularly send URLs with tracking code and getting rid of these is rather cumbersome (much more so than on desktop) so please make this add-on/extension available there too!

Thank you!

**Comment by brandonkal** [comment]
@balazsgerlei In the meantime you may find this web app useful: https://linkcleaner.kalinow.ski
It integrates with the Android share menu for easy use:
Install it as an app, use share menu from Firefox, share with Link Cleaner, and from Link Cleaner click share.
Also works as a Siri shortcut on iOS.

It is a fork of a project of a similar project but with ClearURLs logic instead. For simplicity, it's using an embedded version of the ClearURLs rules.

**Comment by KevinRoebert** [comment]
ClearURLs is now also available on Firefox for Android: https://blog.mozilla.org/addons/2022/12/15/new-extensions-available-now-on-firefox-for-android-nightly/
