### ISSUE TITLE
Bandcamp URLs can be cleaned

### ISSUE THREAD

**Issue by HACKER-3000** [ClearURLs/Addon#269]
Links to Bandcamp albums and tracks can have tracking garbage at the end wich can just be cut.

Uncleaned:
`https://noagreements.bandcamp.com/track/save-me-disavowed?from=search&search_item_id=2443005792&search_item_type=t&search_match_part=%3F&search_page_id=2248967963&search_page_no=0&search_rank=1&logged_in_menubar=true`

Clean:
`https://noagreements.bandcamp.com/track/save-me-disavowed`

This is a VERY ugly RegEx for it: `(https:\/\/[\S]+.bandcamp.com\/(?:track|album)\/[^\/\?]+)\?[\s\S]*$`
Only the first capturing group will be kept, the rest discarded

**Comment by HACKER-3000** [comment]
wait no im stupid therte is a seperate rules repo

**Comment by hydrargyrum** [comment]
@H3wastooshort where's that repo?

**Comment by H3wastooshort** [comment]
https://github.com/ClearURLs/Rules
