### ISSUE TITLE
ClearURLs Addon Breaks Google Sign In's using accounts.google.com | Please Whitelist

### ISSUE THREAD

**Issue by LegendarySpinx** [ClearURLs/Addon#272]
Hi there,

When Using ClearURL's Addon I try to login into an website using Google Account, it says "Something Went Wrong Please Try Again"

But after removing the addon it works fine.

Tested on Edge and Firefox

Please whitelist this domain or fix this problem.

**Comment by jahirfiquitiva** [comment]
I'm facing the same issue. Hope they fix it soon

**Comment by caesay** [comment]
Indeed. This had me pulling my hair out. At the moment if you use Google sign-in this extension is not possible to use!

**Comment by SKEIDs** [comment]
I think this issue is duplicate to https://github.com/ClearURLs/Addon/issues/264#issuecomment-1267824181

**Comment by fawaf** [comment]
very much +1 as well

**Comment by amalic** [comment]
https://github.com/ClearURLs/Addon/issues/255#issuecomment-1358921804

**Comment by agusl88** [comment]
Also breaks the flow of authorizing new apps on google drive/docs

**Comment by patrickdrd** [comment]
same problem here, please fix

**Comment by djo5296** [comment]
bumping this issue cuz it gets annoying having to disable just to log in and all

**Comment by Glinte** [comment]
Facing the same issue

**Comment by zany130** [comment]
Disabling Prevent tracking injection over history API  fixes the issue
![image](https://github.com/ClearURLs/Addon/assets/25832539/9ba94090-8925-4357-9680-a300b27f2210)

**Comment by Driek123** [comment]
> Disabling Prevent tracking injection over history API fixes the issue

That works, just needed to remember to click the "save & reload addon" button at the bottom to actually apply the setting.

**Comment by LegendarySpinx** [comment]
Thanks, it should be mentioned in Chrome Webstore Description for other users as well !
