### ISSUE TITLE
Is there anything like Clear Url List? Which we can add in adblockers like uBlock?

### ISSUE THREAD

**Issue by AdishSagarawat** [ClearURLs/Addon#275]
It would be much better to do so.

Thanks

**Comment by aceace15** [comment]
the main thing of that sort is `➗ Actually Legitimate URL Shortener Tool` from `⚙️ Dandelion Sprout's Annoyances List` and for a port of ClearURLs rules there is this filter list [clearurls for ubo](https://github.com/DandelionSprout/adfilt/tree/master/ClearURLs%20for%20uBo) that you can use (using the direct port could cause issues if Clear Urls hasn't fixed a bad parameter removal)
[see here for the main page to send reports to the people making those lists](https://github.com/DandelionSprout/adfilt/discussions/163)

going back to  the first filter list, it's recommended to use this it by [arcanefox](https://github.com/arkenfox/user.js), as well as being bundled in by [librewolf](https://librewolf.net/)

to manually add the filters to ublock first go into the ublock settings and then on the second tab named filter lists, at the bottom of the page there is an import option to add new filters (which you paste the link to the raw version of the filter)
to add the `➗ Actually Legitimate URL Shortener Tool` you should add this link into the import box `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt`
and for the port of Clear URls list then import this one
 `https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt`

**Comment by AdishSagarawat** [comment]
Thanks a lot,
It worked :)
