### ISSUE TITLE
Randomly generated invalid ETag leads to HTTP 400 from Apache Tomcat

### ISSUE THREAD

**Issue by xnoreq** [ClearURLs/Addon#276]
Hello,

https://github.com/ClearURLs/Addon/blob/628faf0e85919f5eea64e1ac40bf0bd781708e98/core_js/eTagFilter.js#L46

causes Firefox to send an invalid If-None-Match header like this:
`If-None-Match: 0.17188988542931039`

The ETag is supposed to be a quoted string of ASCII characters, optionally with a `W/` prefix, see:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag#examples

This causes Apache Tomcat to fail all requests with a HTTP 400 (Bad Request).

**Comment by KevinRoebert** [comment]
Thanks for the bug report. I will write a fix as soon as possible.

**Comment by xnoreq** [comment]
Hey, thanks. Is this in the 1.26.0 release, because I'm still seeing floating point numbers in requests in Firefox?

**Comment by KevinRoebert** [comment]
> Hey, thanks. Is this in the 1.26.0 release, because I'm still seeing floating point numbers in requests in Firefox?

No, it's on the master branch.

**Comment by alee94240** [comment]
Hi there
