### ISSUE TITLE
ClearURL version delay in Github vs majorgeeks?

### ISSUE THREAD

**Issue by pstein** [ClearURLs/Addon#325]
Why are the ClearURL download versions here in Github always far behind the versions on majorgeeks:

https://www.majorgeeks.com/files/details/clearurls.html

Shouldn't be github the primary source of  releases?

**Comment by KevinRoebert** [comment]
Oops. I had forgotten to change the settings from "Draft" to "Release". Now they should be visible to everyone.

**Comment by pstein** [comment]
Still a delay:

Majorgeeks.com shows v1.26.1 while github only v1.26
