### ISSUE TITLE
Not working on a particular website

### ISSUE THREAD

**Issue by lamyergeier** [ClearURLs/Addon#355]
On the website when I click links it adds some text at the end of the url. For example, following is a snippet from the URL

> You should find it in most Linux distributions through the default repositories. But, if you need help installing, go through the [[GitHub page](https://github.com/gnome-terminator/terminator?ref=itsfoss.com)](https://github.com/gnome-terminator/terminator?ref=itsfoss.com).

We can see that it adds `?ref=itsfoss.com`

Why does the extension doesn't removes that? What should I do?

**Comment by KevinRoebert** [comment]
That is correct and due to this line: https://github.com/ClearURLs/Rules/blob/master/data.min.json#L329. This is done due to a request from GitHub, that they actually need this parameter, see https://gitlab.com/ClearURLs/rules/-/merge_requests/12
