### ISSUE TITLE
[Rule](https://space.bilibili.com/272654283)=?spm_id_from=

### ISSUE THREAD

**Issue by Aicnal** [ClearURLs/Addon#382]
The `=?spm_id_from` is the tracker code
Remove - ?spm_id_from=333.1007.tianma.18-3-69.click
Example - https://space.bilibili.com/272654283?spm_id_from=333.1007.tianma.18-3-69.click

**Comment by sncix** [comment]
I've opened a merge request on GitLab: https://gitlab.com/ClearURLs/rules/-/merge_requests/59

**Comment by Aicnal** [comment]
> I've opened a merge request on GitLab: https://gitlab.com/ClearURLs/rules/-/merge_requests/59

OK. And now I will close this issue.
