### ISSUE TITLE
ClearURLs fails the eTag test at Cookieless Cookies.

### ISSUE THREAD

**Issue by Peacock365** [ClearURLs/Addon#67]
Dear ClearURLs developer(s),

I found that the ClearURLs extension fails the Cookieless Cookies test at:

http://lucb1e.com/rp/cookielesscookies/

This webpage uses eTags. Steps to reproduce:

1. Go to the link above.
2. Close the tab.
3. Go to the link above again in a new tab.

The visit count goes up, but it really shouldn't, if the eTags were properly blocked. Please take a look at this.

_My setup: ClearURLs 1.19.0, Brave 1.12.114 (Chromium 84.0.4147.135), macOS 10.15.6 Catalina._

**Comment by KevinRoebert** [comment]
I know about this problem. Unfortunately, the eTag filtering under Chrome does not work correctly at the moment. Under Firefox everything is cleaned up correctly. I have to find out why this is the case.

**Comment by KevinRoebert** [comment]
Related to: https://gitlab.com/KevinRoebert/ClearUrls/-/issues/524

**Comment by Peacock365** [comment]
As someone mentioned in your GitLab repo, the extension "Trace" seems to pass the test on Chromium. Searching for "eTag" in their repo brings this up:

https://github.com/jake-cryptic/AbsoluteDoubleTrace/search?q=eTag&unscoped_q=eTag

**Comment by KevinRoebert** [comment]
Should be fixed

**Comment by Peacock365** [comment]
Almost two years later you got around to it. Thought it was fixed now. It wasn't.

Still fails the above test as well as https://hinternesch.com/page1
