### ISSUE TITLE
AMP URL cannot be opened

### ISSUE THREAD

**Issue by bersbersbers** [ClearURLs/Addon#71]
https://www.google.com/amp/s/de.statista.com/infografik/amp/22496/anzahl-der-gesamten-positiven-corona-tests-und-positivenrate/ (saved as a bookmark on mobile) redirects to chrome-extension://lckanjgmijmafbedllaakclkaicjfmnk/de.statista.com/infografik/amp/22496/anzahl-der-gesamten-positiven-corona-tests-und-positivenrate/

**Comment by KevinRoebert** [comment]
Should be fixed in the new version. Duplicate to: https://gitlab.com/KevinRoebert/ClearUrls/-/issues/739

**Comment by KevinRoebert** [comment]
Is fixed in v.1.20.0
