### ISSUE TITLE
Off-topic question: Where is the "Get the addon" badge from?

### ISSUE THREAD

**Issue by realpixelcode** [ClearURLs/Addon#79]
Where did you get this badge from? I've looked everywhere but I found only a deprecated version: https://blog.mozilla.org/addons/2015/11/10/promote-your-add-ons-with-the-get-the-add-on-button/

Thanks

![](https://camo.githubusercontent.com/a35101b0e594cf92ffbe74bd3638d7fe45085ff038d6e760f79db605223a8e27/68747470733a2f2f626c6f672e6d6f7a696c6c612e6f72672f6164646f6e732f66696c65732f323032302f30342f6765742d7468652d6164646f6e2d66782d6170722d323032302e737667)

**Comment by KevinRoebert** [comment]
I've got this from Mozillas extension workshop page: https://extensionworkshop.com/documentation/publish/promoting-your-extension/#promote-your-addon

It was promoted via Mozilla's Addon Developer email list. Can also find the *.svg version on this page: https://blog.mozilla.org/addons/files/2020/04/get-the-addon-fx-apr-2020.svg

**Comment by realpixelcode** [comment]
Thank you very much ☺️
