### ISSUE TITLE
Twitter URL broken

### ISSUE THREAD

**Issue by bersbersbers** [ClearURLs/Addon#91]
Original link:
> https://s2.washingtonpost.com/2e46378/

Redirects to:
> https://twitter.com/AnimalsWorId/status/1347212769716629505?s=20&=

Is distorted to:
> https://twitter.com/AnimalsWorId/status/1347212769716629505?=

Result:
> Something went wrong.

(One might argue the "distorted" link is as correct as the original one, but Twitter accepts the first and rejects the second.)

**Comment by Shnoulle** [comment]
2nd link is OK for me on Firefox or copy paste to Chrome.

**Comment by bersbersbers** [comment]
Sure - the problem is that the 2nd link (working) is converted to the 3rd (not working) when you click the 1st.

**Comment by Shnoulle** [comment]
No i mean : i copy/paste `https://twitter.com/AnimalsWorId/status/1347212769716629505?=` on chrome : it work

And with ClearUrls activate :  `https://s2.washingtonpost.com/2e46378/` 1st link is OK too

![Capture d’écran du 2021-01-27 17-45-47](https://user-images.githubusercontent.com/1439428/106023928-8faa6780-60c7-11eb-929a-b6fc3055447c.png)

**Comment by bersbersbers** [comment]
I tried again just now, in Chrome:
1. https://s2.washingtonpost.com/2e46378/: "Something went wrong."
2. https://twitter.com/AnimalsWorId/status/1347212769716629505?s=20&= works indeed
3. https://twitter.com/AnimalsWorId/status/1347212769716629505?= also works
But I could not reproduce this in Incognito mode, so it may be related to my having other extensions installed. It turned out to be Privacy Badger - sorry for the noise.

https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp

**Comment by bersbersbers** [comment]
(Also, it only happens when logged in to Twitter - another factor that makes this issue more difficult to reproduce.)

**Comment by bersbersbers** [comment]
I filed https://github.com/EFForg/privacybadger/issues/2737.
